services:
  server:
    image: 528424611297.dkr.ecr.us-east-1.amazonaws.com/bia:${TAG}
    container_name: bia
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: 819vNypHGMBs0euUEGwB
      DB_PORT: 5432
      DB_HOST: bia.cgbk82so41lk.us-east-1.rds.amazonaws.com
   